orig:
	g++ -Wall -o 5-2_orig 5-2_orig.cpp

vec1:
	g++ -Wall -o 5-2_vec_1 5-2_vec_1.cpp

vec2:
	g++ -Wall -o 5-2_vec_2 5-2_vec_2.cpp

vec3:
	g++ -Wall -o 5-2_vec_3 5-2_vec_3.cpp

vec4:
	g++ -Wall -o 5-2_vec_4 5-2_vec_4.cpp
